'use client'
import "./globals.css";
import type { Metadata } from "next";
import {SessionProvider} from 'next-auth/react';
import { Inter, } from "next/font/google";
import Navbar from "./components/Navbar/Navbar";
import { Roboto, Noto_Sans_KR } from "next/font/google"; // Roboto와 한글 NotoSans를 사용합니다.
import { cls } from "../util/cls";

const notoSansKr = Noto_Sans_KR({
  // preload: true, 기본값
  subsets: ["latin"], // 또는 preload: false
  weight: ["100", "400", "700", "900"], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
});

const roboto = Roboto({
  subsets: ["latin"], // preload에 사용할 subsets입니다.
  weight: ["100", "400", ],
  variable: "--roboto", // CSS 변수 방식으로 스타일을 지정할 경우에 사용합니다.
});


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) 
{
  return (
    <html lang="en">
        <body className={`${cls(inter.className , notoSansKr.className, roboto.variable)}`}>
          <SessionProvider>
            <Navbar />
            {children}
          </SessionProvider> 
        </body>
    </html>
    
  );
}
